window.MISSOES = window.MISSOES || {};
MISSOES['sociologia'] = [
 {
  "aposTitulo": "O conhecimento em Ciências Sociais: Durkheim, Weber e Marx",
  "missao": {
   "id": "soc-mis-01",
   "fonte": "UEL 2025 · 2º dia · sociologia · Questão 2",
   "tipo": "dissertativa",
   "enunciado": "<p>Segundo o sociólogo francês, Émile Durkheim, os indivíduos se organizam em coletividades a partir de seus vínculos sociais, que implicam em dois tipos de solidariedade: a mecânica e a orgânica. Durkheim desenvolveu os conceitos de solidariedade mecânica e solidariedade orgânica para explicar as mudanças na sociedade francesa (ou sociedades europeias) advindas das transformações decorrentes da revolução industrial, em curso no século XIX. Em relação a esses dois tipos de solidariedade, o autor afirma que</p><p>não só, de maneira geral, a solidariedade mecânica liga os homens menos fortemente do que a solidariedade orgânica, como também, à medida que avançamos na evolução social, ela vai se afrouxando cada vez mais. (DURKHEIM, È. Da divisão do trabalho social. São Paulo: Martins Fontes, 2010. p.133. Biblioteca do pensamento moderno.)</p><p>Com base no texto e nos conhecimentos sobre o tema, defina as diferenças entre os conceitos de solidariedade mecânica e solidariedade orgânica e explique por que, segundo Durkheim, a solidariedade orgânica passa a ligar mais fortemente as pessoas com o avanço social, especialmente em relação à divisão do trabalho.</p>",
   "gabarito": "<p>pessoas realizam atividades semelhantes e compartilham valores e crenças comuns. A coesão social é mantida pela homogeneidade dos indivíduos. Exemplo de sociedade com predomínio de solidariedade mecânica são comunidades rurais pequenas. Já a solidariedade orgânica predomina em sociedades mais complexas e modernas, onde há grande divisão do trabalho. As pessoas desempenham funções especializadas e interdependentes, o que cria uma coesão social baseada na necessidade mútua, como nas sociedades industriais. A solidariedade orgânica passa a ligar mais fortemente as pessoas com o avanço social, segundo Durkheim, porque, à medida que a sociedade avança e se torna mais complexa, ocorre uma maior divisão do trabalho. Isso significa que as pessoas se especializam em diferentes funções e dependem umas das outras para satisfazer suas necessidades. Essa interdependência cria laços sociais mais fortes, pois cada indivíduo precisa dos outros para sobreviver e prosperar. A solidariedade orgânica, portanto, se torna mais forte porque a coesão social é baseada na colaboração e na complementaridade das funções, ao contrário da solidariedade mecânica, que se baseia na semelhança entre os indivíduos.</p><small>Resposta esperada oficial (COPS/UEL).</small>",
   "minimo": 80,
   "link": "material/provas/uel/2025/2025-2dia-discursiva-sociologia.pdf",
   "criterios": "Conteúdo programático oficial: O Conhecimento em Ciências Sociais: introdução ao estudo da sociedade, teoria e método.. A banca avalia se a resposta traz os pontos da resposta esperada, com clareza e vocabulário da disciplina.",
   "tema": "O Conhecimento em Ciências Sociais: introdução ao estudo da sociedade, teoria e método.",
   "nivel": "dificil"
  }
 },
 {
  "aposTitulo": "Política, Estado, dominação e poder",
  "missao": {
   "id": "soc-mis-02",
   "fonte": "UEL 2025 · 2º dia · sociologia · Questão 1",
   "tipo": "dissertativa",
   "enunciado": "<p>Leia o texto a seguir.</p><p>De acordo com o sociólogo alemão Max Weber, a legitimidade das formas de dominação se apoia em três tipos: dominação legal, dominação tradicional e dominação carismática. Segundo Weber, a dominação legal tem seu fundamento de poder baseado em um estatuto e “seu tipo mais puro é a dominação burocrática. Sua ideia básica é: qualquer direito pode ser criado e modificado mediante um estatuto sancionado corretamente quanto à forma”. Já a legitimidade da dominação tradicional ocorre “em virtude da crença na santidade das ordenações e dos poderes senhoriais há muito existentes”. [...]. “Obedece-se à pessoa em virtude de sua dignidade própria, santificada pela tradição: por fidelidade. O conteúdo das ordens está fixado pela tradição, cuja violação desconsiderada por parte do senhor poria em perigo a legitimidade do seu próprio domínio, que repousa exclusivamente na santidade delas”. (WEBER, M. Sociologia. Coleção grandes cientistas sociais, n.13. São Paulo: Ática, 1979. p.128 e p.131.)</p><p>Com base no texto e nos conhecimentos sobre a teoria de Max Weber, explique o que fundamenta a dominação carismática e como esse conceito (tipos de dominação) pode ser aplicado para a compreensão de processos sociais e políticos contemporâneos.</p>",
   "gabarito": "<p>Os três tipos de dominação – legal, tradicional e carismática – ajudam a explicar as tensões políticas e sociais na sociedade moderna. A dominação carismática, segundo Max Weber, é fundamentada no carisma de uma pessoa, ou seja, nas qualidades extraordinárias e excepcionais que ela possui, as quais são reconhecidas e valorizadas por seus seguidores. Esse tipo de dominação não depende de regras ou tradições estabelecidas, mas, sim, da devoção e confiança pessoal que as pessoas têm no líder carismático. Líderes carismáticos também surgem na política, mobilizando uma nova base de apoio com seu carisma e sua visão ideológica. Essas formas de dominação podem interagir de diversas maneiras. Um líder carismático pode ascender ao poder e depois institucionalizar seu governo, transformando sua dominação carismática em uma dominação legal. Ao mesmo tempo, elementos tradicionais podem ser incorporados em sistemas legais para fortalecer a legitimidade do governo aos olhos de certos grupos sociais, o que tem acontecido em vários países. Boa parte dos conflitos políticos nas sociedades modernas resultam da complexa combinação entre esses diferentes tipos de dominação, colocando em confronto a tradição, o poder constitucional legal e o carisma das lideranças.</p><small>Resposta esperada oficial (COPS/UEL).</small>",
   "minimo": 80,
   "link": "material/provas/uel/2025/2025-2dia-discursiva-sociologia.pdf",
   "criterios": "Conteúdo programático oficial: Política / Estado, Dominação e Poder – As várias formas de poder e dominação. A banca avalia se a resposta traz os pontos da resposta esperada, com clareza e vocabulário da disciplina.",
   "tema": "Política / Estado, Dominação e Poder – As várias formas de poder e dominação",
   "nivel": "dificil"
  }
 },
 {
  "aposTitulo": "Cultura, diversidade e identidade",
  "missao": {
   "id": "soc-mis-03",
   "fonte": "UEL 2021 · fase única · Questão 12",
   "tipo": "objetiva",
   "tema": "Cultura e diversidade cultural",
   "nivel": "medio",
   "enunciado": "<p>De acordo com Priscila Tapajowara, indígena e ativista: Em nossa cultura indígena, [...] vivemos em comunhão com o próximo. Nós compartilhamos utensílios domésticos, dividimos o mesmo espaço de convivência, em nossas habitações vivem muitas pessoas, o que facilita o contágio de doenças infecciosas. [...] Ao longo da história, [...] nós povos indígenas viemos sofrendo grandes massacres e muitos povos foram dizimados. [...] Outro fator que dizimou povos inteiros foram as doenças trazidas pelo homem branco. Doenças infectocontagiosas, como gripe, sarampo, tuberculose e varíola, [...] foram umas das responsáveis pela redução da nossa população. TAPAJOWARA, Priscila. Disponível em: www.uol.com.br. Com base no texto e nos conhecimentos sobre Antropologia, assinale a alternativa correta.</p>",
   "opcoes": [
    "A relação entre povos indígenas e povos não indígenas deve fundamentar-se no etnocentrismo, conceito segundo o qual há respeito e compreensão sobre as especificidades e diferenças culturais.",
    "A expressão “Em nossa cultura indígena”, utilizada pela ativista, afirma que tal cultura é heterogênea e que os povos indígenas estão integrados à sociedade brasileira.",
    "Nas duas últimas décadas, no Brasil, as políticas indigenistas têm se baseado em ideias evolucionistas e em práticas de tutela e assimilação cultural, visando promover a evolução cultural destes povos.",
    "Parte dos povos indígenas do Brasil, por suas especificidades culturais e condições objetivas de sobrevivência, está mais sujeita a doenças infecciosas.",
    "A constituição física dos indígenas, em razão do seu estado de vida natural, garante a eles maior imunidade às doenças infecciosas oriundas de povos não indígenas."
   ],
   "correta": 3,
   "resolucao": "Gabarito oficial: <b>d)</b>.<br>a) Incorreta. Etnocentrismo é um importante conceito antropológico, que pressupõe a classificação e hierarquização das diferentes culturas, a partir de uma (cultura) tomada como centro, como referência. Uma postura etnocêntrica é uma postura de superioridade, não de compreensão e respeito às especificidades culturais. Nos termos da Antropologia, de forma alguma o etnocentrismo deve fundamentar a relação entre povos indígenas e não indígenas<br>b) Incorreta. No texto de referência, a expressão “em nossa cultura indígena”, indica que se trata de ressaltar as especificidades dessa cultura em relação à cultura não indígena. Não é possível inferir da mesma frase que ela se refira às especificidades vinculadas às próprias variações entre as diferentes culturas indígenas. Desse modo, a afirmação da ativista, pelos termos utilizados (“nossa cultura indígena”), supõe homogeneidade da cultura indígena e não heterogeneidade. Em segundo lugar, a frase não permite supor que haja integração da cultura indígena à cultura brasileira como um todo. Ao contrário, o texto no qual se insere a expressão, indica que os povos indígenas estão à margem dos direitos sociais básicos garantidos pela Constituição Nacional. A cultura indígena resiste e mantém suas especificidades, apesar do contato com os povos não indígenas.<br>c) Incorreta. A afirmativa está incorreta pois, nas últimas duas décadas, as políticas implementadas pelos órgãos competentes, não se referem à ideia de assimilação cultural e nem à sugestão de promover a “evolução cultural destes povos”. Desde a Constituição de 1988, as políticas indígenas vem passando por orientações que firmam novos paradigmas conceituais e jurídicos. Extingue-se a figura da tutela e garante-se o reconhecimento da autonomia e dos direitos decorrentes das especificidades culturais dos povos indígenas no país. Rompe-se, também, com o paradigma assistencialista vigente até então.<br>d) Correta. Segundo Priscila Tapajowara, no texto de referência, os povos indígenas dividem espaços de convivência, compartilham utensílios domésticos, alimentos, etc. A autora lembra ainda que povos indígenas já foram dizimados por doenças como gripe e sarampo em diversos momentos históricos. Por essas especificidades e condições, é correto afirmar que estão mais sujeitos ao contágio de diversas doenças infecciosas.<br>e) Incorreta. No texto informado, destaca-se a maior vulnerabilidade dos povos indígenas, em função de seus hábitos culturais que podem facilitar a transmissão de doenças infectocontagiosas, tais como gripe, sarampo, tuberculose, varíola. Em nenhum momento afirma-se que por seu estado de vida natural, eles estariam imunes às doenças de povos não indígenas.<br><small>Fonte: UEL 2021 · fase única · Questão 12, caderno comentado pela COPS/UEL.</small>",
   "link": "material/provas/uel/2021/2021-fase-unica-caderno-comentado-ingles-tipo1.pdf"
  }
 },
 {
  "aposTitulo": "Estrutura, estratificação e desigualdade",
  "missao": {
   "id": "soc-mis-04",
   "fonte": "UEL 2019 · 1ª fase · Questão 54",
   "tipo": "objetiva",
   "tema": "Estrutura e estratificação social",
   "nivel": "medio",
   "enunciado": "<p>Leia o texto a seguir. A distância entre ricos e pobres tem aumentado na maioria dos países. Estudos do FMI e da OCDE afirmam que isso prejudica o crescimento econômico, mas nem todos os economistas concordam. Economistas não têm a reputação de terem compaixão: seus olhos estão voltados para números, e não para destinos humanos. Assim, a maioria não vê problemas na desigualdade de renda ou de propriedade. BECKER, A. A desigualdade é boa ou ruim para a economia? noticias.uol.com.br. As recentes discussões sobre distâncias sociais entre classes, ou estratos de classe, envolvem também definições e explicações sobre a pobreza e a desigualdade. Com base nos conhecimentos sobre o tema pobreza e desigualdade, assinale a alternativa correta.</p>",
   "opcoes": [
    "Celso Furtado identifica que as origens da desigualdade brasileira decorrem de nossa tradição autocrática, que impediu a formação de uma burguesia autônoma.",
    "Malthus atribui a causa da pobreza à baixa taxa de natalidade, o que reduziria a massa salarial das famílias de baixa renda.",
    "Amartya Sen considera que a eliminação da pobreza depende diretamente do crescimento econômico, pois este assegura benefício a todos os grupos sociais.",
    "Hayek propõe a redução do Estado como meio de gerar maior eficiência econômica, contrapondo-se assim às políticas do Welfare State.",
    "Keynes aponta que a redução dos gastos públicos é uma variável essencial para o estabelecimento do crescimento econômico e do bem-estar social."
   ],
   "correta": 3,
   "resolucao": "Gabarito oficial: <b>d)</b>.<br>a) Incorreta. Celso Furtado identifica, na história da formação econômica colonial do país, as explicações sobre as desigualdades existentes no Brasil e seu elevado patamar. Tal processo foi construído de modo a produzir desequilíbrios sociais, regionais e setoriais, o que explica as origens da extrema desigualdade existente no Brasil.<br>b) Incorreta. A tese malthusiana, muito difundida em diferentes meios, concebe a alta taxa de natalidade, isto é, a superpopulação, como causa da pobreza.<br>c) Incorreta. A tese de Amartya Sen justamente relativiza a associação entre redução da pobreza e crescimento econômico. Tal relação não é direta e pode ocorrer simultaneamente o crescimento econômico com a expansão da pobreza. Isso ocorre porque os benefícios gerados com o crescimento econômico raramente são igualmente distribuídos entre diferentes grupos sociais e podem, inclusive, ser monopolizados por alguns grupos.<br>d) Correta. Hayek foi um importante defensor da liberdade econômica, ou liberdade de mercado, logo, da redução da presença do Estado na economia. Suas ideias influenciam fortemente as políticas neoliberais e se contrapunham ao Estado de Bem-Estar Social – Welfare State, defendido pelo programa de Beveridge.<br>e) Incorreta. Para Keynes, o Estado, por meio do gasto público, tem importante papel para a promoção das políticas anticíclicas, as quais resultam no chamado “círculo virtuoso” para a economia, uma relação positiva entre emprego, demanda e crescimento.<br><small>Fonte: UEL 2019 · 1ª fase · Questão 54, caderno comentado pela COPS/UEL.</small>",
   "link": "material/provas/uel/2019/2019-1fase-caderno-comentado-tipo1.pdf"
  }
 },
 {
  "aposTitulo": "Trabalho, natureza e mudança social",
  "missao": {
   "id": "soc-mis-05",
   "fonte": "UEL 2019 · 1ª fase · Questão 57",
   "tipo": "objetiva",
   "tema": "Relação homem e natureza e o trabalho",
   "nivel": "medio",
   "enunciado": "<p>Leia o texto a seguir. O prefixo “des” indica anomalia. “Desemprego” é o nome de uma condição claramente temporária e anormal, e, assim, a natureza transitória e curável da doença é patente. A noção de “desemprego” herdou sua carga semântica da auto consciência de uma sociedade que costumava classificar seus integrantes, antes de tudo, como produtores, e que também acreditava no pleno emprego não apenas como condição desejável e atingível, mas também como seu derradeiro destino. Uma sociedade que, portanto, classificava o emprego como uma chave – a chave – para a solução dos problemas ao mesmo tempo da identidade pessoal socialmente aceitável, da posição social segura, da sobrevivência individual e coletiva, da ordem social e da reprodução sistêmica. BAUMAN, Z. Vidas despedaçadas. Rio de Janeiro: Jorge Zahar, 2005. p. 19. Com base no texto e nos conhecimentos sobre as transformações mais recentes quanto ao tema desemprego no capitalismo, considere as afirmativas a seguir.</p><p>I. A tendência no capitalismo globalizado é tornar os postos de trabalho mais flexíveis para atender necessidades das grandes corporações, levando a questionamentos do modelo taylorista-fordista.</p><p>II. A perda de identidade em relação ao emprego no capitalismo contemporâneo confirma o fato de que a categoria trabalho deixou de ser essencial para a produção e reprodução da vida social.</p><p>III. As políticas antissindicais que acompanham as práticas neoliberais apresentam como resultado a supressão das crises econômicas globais com o restabelecimento do pleno emprego.</p><p>IV. O desemprego, no capitalismo globalizado, tem a longa duração como seu traço característico, enquanto avança o emprego precário e de alta rotatividade, como nos call centers.</p><p>Assinale a alternativa correta.</p>",
   "opcoes": [
    "Somente as afirmativas I e II são corretas.",
    "Somente as afirmativas I e IV são corretas.",
    "Somente as afirmativas III e IV são corretas.",
    "Somente as afirmativas I, II e III são corretas.",
    "Somente as afirmativas II, III e IV são corretas."
   ],
   "correta": 1,
   "resolucao": "Gabarito oficial: <b>b)</b>.<br>I. Correta. A flexibilização das relações de trabalho e das normas trabalhistas tem sido uma das características marcantes do capitalismo globalizado ou mundializado. Com isso, as grandes corporações buscam dar conta de seus problemas de taxa de lucro, recorrendo, em contrapartida, a modificações no antigo modelo produtivo ancorado nas práticas propostas pelo taylorismo-fordismo, que propunham um modo de organização do trabalho essencialmente rígido, seja pelo cronômetro e fragmentação da atividade de trabalho, seja pela linha de montagem com a esteira rolante.<br>II. Incorreta. Embora estudos apontem para a perda da identidade com o trabalho, como é o caso de André Gorz, em seu clássico livro Adeus ao proletariado, que remete à imagem da “não-classe-dos-não-trabalhadores”, como também em significativa parte da produção recente que fala em “fim da sociedade do trabalho”, toda e qualquer forma de sociedade continuará dependendo da mediação das forças vitais humanas com a natureza, ou seja, as condições objetivas, para realizar seu processo sociometabólico de existência do gênero humano. Portanto, o trabalho independentemente da forma de sociabilidade humana constitui a essência do ser social.<br>III. Incorreta. As práticas antissindicais desenvolvidas pelas empresas ao redor do mundo não têm garantido a realização do pleno emprego nem o fim das crises econômicas. Pelo contrário, quanto maior a dificuldade de organização sindical, conforme revelam vários estudos na área de sociologia do trabalho, maiores são as tendências de precarização do emprego e demissões de coletivos de trabalhadores.<br>IV. Correta. A partir dos anos 1970, a explosão mundial do desemprego e a escassez de postos de trabalho estabeleceram um novo perfil junto à força de trabalho. Ao contrário do período denominado “os trinta gloriosos”, quando predominava o “pleno emprego”, o quadro pós 1970, em diversos países, apontou para que o desemprego passou a ser de longa duração e seletivo, atingindo mais intensamente os desqualificados em relação aos qualificados. Os estudos apontam, também, para desvantagens das mulheres em relação aos homens no que se refere à manutenção do emprego e também o crescimento dos chamados empregos modelo Mac Donald’s, que possuem por característica a baixa remuneração, a alta rotatividade e a precarização das relações de emprego.<br><small>Fonte: UEL 2019 · 1ª fase · Questão 57, caderno comentado pela COPS/UEL.</small>",
   "link": "material/provas/uel/2019/2019-1fase-caderno-comentado-tipo1.pdf"
  }
 }
];
